
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AppSpecificAppSidebar: typeof import("../../app/components/app-specific/AppSidebar.vue")['default']
  AppSpecificCanVue: typeof import("../../app/components/app-specific/Can.vue.vue")['default']
  AppSpecificDragHandle: typeof import("../../app/components/app-specific/DragHandle.vue")['default']
  AppSpecificDraggableRow: typeof import("../../app/components/app-specific/DraggableRow.vue")['default']
  AppSpecificNavUser: typeof import("../../app/components/app-specific/NavUser.vue")['default']
  AppSpecificToastContainer: typeof import("../../app/components/app-specific/Toast/toastContainer.vue")['default']
  AppSpecificComponentsAmmunitionTypesTab: typeof import("../../app/components/app-specific/components/AmmunitionTypesTab.vue")['default']
  AppSpecificComponentsArmoryTab: typeof import("../../app/components/app-specific/components/ArmoryTab.vue")['default']
  AppSpecificComponentsFirearmsTab: typeof import("../../app/components/app-specific/components/FirearmsTab.vue")['default']
  AppSpecificComponentsPendingApprovalTab: typeof import("../../app/components/app-specific/components/PendingApprovalTab.vue")['default']
  AppSpecificDialogsConfirmationDialog: typeof import("../../app/components/app-specific/dialogs/ConfirmationDialog.vue")['default']
  AppSpecificDialogsTransferConfirmationDialog: typeof import("../../app/components/app-specific/dialogs/TransferConfirmationDialog.vue")['default']
  AppSpecificDialogsAmmunitionAddAmmoInventory: typeof import("../../app/components/app-specific/dialogs/ammunition/AddAmmoInventory.vue")['default']
  AppSpecificDialogsAmmunitionAdjustInventory: typeof import("../../app/components/app-specific/dialogs/ammunition/AdjustInventory.vue")['default']
  AppSpecificDialogsAmmunitionDetails: typeof import("../../app/components/app-specific/dialogs/ammunition/AmmunitionDetails.vue")['default']
  AppSpecificDialogsAmmunitionModal: typeof import("../../app/components/app-specific/dialogs/ammunition/AmmunitionModal.vue")['default']
  AppSpecificDialogsAmmunitionTypeModal: typeof import("../../app/components/app-specific/dialogs/ammunition/AmmunitionTypeModal.vue")['default']
  AppSpecificDialogsAmmunitionRegisterAmmoType: typeof import("../../app/components/app-specific/dialogs/ammunition/RegisterAmmoType.vue")['default']
  AppSpecificDialogsArmsregisterCreateArmoryModal: typeof import("../../app/components/app-specific/dialogs/armsregister/CreateArmoryModal.vue")['default']
  AppSpecificDialogsArmsregisterDisposeFireArm: typeof import("../../app/components/app-specific/dialogs/armsregister/DisposeFireArm.vue")['default']
  AppSpecificDialogsArmsregisterFireArmsDetails: typeof import("../../app/components/app-specific/dialogs/armsregister/FireArmsDetails.vue")['default']
  AppSpecificDialogsArmsregisterRecordFireArm: typeof import("../../app/components/app-specific/dialogs/armsregister/RecordFireArm.vue")['default']
  AppSpecificDialogsArmsregisterRegisterFireArm: typeof import("../../app/components/app-specific/dialogs/armsregister/RegisterFireArm.vue")['default']
  AppSpecificDialogsArmsregisterReviewFireArm: typeof import("../../app/components/app-specific/dialogs/armsregister/ReviewFireArm.vue")['default']
  AppSpecificDialogsBranchModal: typeof import("../../app/components/app-specific/dialogs/BranchModal.vue")['default']
  AppSpecificDialogsFirearmIssueFireArm: typeof import("../../app/components/app-specific/dialogs/firearm/IssueFireArm.vue")['default']
  AppSpecificDialogsFirearmReturnFireArm: typeof import("../../app/components/app-specific/dialogs/firearm/ReturnFireArm.vue")['default']
  AppSpecificDialogsLocationModal: typeof import("../../app/components/app-specific/dialogs/location/LocationModal.vue")['default']
  AppSpecificDialogsRolesRoleModal: typeof import("../../app/components/app-specific/dialogs/roles/RoleModal.vue")['default']
  AppSpecificDialogsSecuritydevicesDeviceDetails: typeof import("../../app/components/app-specific/dialogs/securitydevices/DeviceDetails.vue")['default']
  AppSpecificDialogsSecuritydevicesDeviceInspection: typeof import("../../app/components/app-specific/dialogs/securitydevices/DeviceInspection.vue")['default']
  AppSpecificDialogsSecuritydevicesSecurityDeviceModal: typeof import("../../app/components/app-specific/dialogs/securitydevices/SecurityDeviceModal.vue")['default']
  AppSpecificDialogsUsersAddEdit: typeof import("../../app/components/app-specific/dialogs/users/AddEdit.vue")['default']
  AppSpecificDialogsUsersInfoField: typeof import("../../app/components/app-specific/dialogs/users/InfoField.vue")['default']
  AppSpecificDialogsUsersUserDetails: typeof import("../../app/components/app-specific/dialogs/users/UserDetails.vue")['default']
  AppSpecificDialogsUsersUserModal: typeof import("../../app/components/app-specific/dialogs/users/UserModal.vue")['default']
  AppSpecificFormsAllocationForm: typeof import("../../app/components/app-specific/forms/AllocationForm.vue")['default']
  AppSpecificFormsAmmunitionForm: typeof import("../../app/components/app-specific/forms/AmmunitionForm.vue")['default']
  AppSpecificFormsCreateIssuanceForm: typeof import("../../app/components/app-specific/forms/CreateIssuanceForm.vue")['default']
  AppSpecificFormsFireArmForm: typeof import("../../app/components/app-specific/forms/FireArmForm.vue")['default']
  AppSpecificFormsFirearmReturnDialog: typeof import("../../app/components/app-specific/forms/FirearmReturnDialog.vue")['default']
  AppSpecificFormsLoginForm: typeof import("../../app/components/app-specific/forms/LoginForm.vue")['default']
  AppSpecificFormsRoleForm: typeof import("../../app/components/app-specific/forms/RoleForm.vue")['default']
  AppSpecificFormsSetupBranchForm: typeof import("../../app/components/app-specific/forms/SetupBranchForm.vue")['default']
  AppSpecificFormsUserForm: typeof import("../../app/components/app-specific/forms/UserForm.vue")['default']
  AppSpecificPartialPageAmmunitions: typeof import("../../app/components/app-specific/partial-page/ammunitions.vue")['default']
  AppSpecificPartialPageFirearms: typeof import("../../app/components/app-specific/partial-page/firearms.vue")['default']
  AppSpecificPartialPageKits: typeof import("../../app/components/app-specific/partial-page/kits.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  Accordion: typeof import("../../app/components/ui/accordion/index")['Accordion']
  AccordionContent: typeof import("../../app/components/ui/accordion/index")['AccordionContent']
  AccordionItem: typeof import("../../app/components/ui/accordion/index")['AccordionItem']
  AccordionTrigger: typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']
  Alert: typeof import("../../app/components/ui/alert/index")['Alert']
  AlertDescription: typeof import("../../app/components/ui/alert/index")['AlertDescription']
  AlertTitle: typeof import("../../app/components/ui/alert/index")['AlertTitle']
  AlertDialog: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']
  AlertDialogAction: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']
  AlertDialogCancel: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']
  AlertDialogContent: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']
  AlertDialogDescription: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']
  AlertDialogFooter: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']
  AlertDialogHeader: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']
  AlertDialogTitle: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']
  AlertDialogTrigger: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
  Avatar: typeof import("../../app/components/ui/avatar/index")['Avatar']
  AvatarFallback: typeof import("../../app/components/ui/avatar/index")['AvatarFallback']
  AvatarImage: typeof import("../../app/components/ui/avatar/index")['AvatarImage']
  Badge: typeof import("../../app/components/ui/badge/index")['Badge']
  Breadcrumb: typeof import("../../app/components/ui/breadcrumb/index")['Breadcrumb']
  BreadcrumbEllipsis: typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']
  BreadcrumbItem: typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbItem']
  BreadcrumbLink: typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbLink']
  BreadcrumbList: typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbList']
  BreadcrumbPage: typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbPage']
  BreadcrumbSeparator: typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']
  Button: typeof import("../../app/components/ui/button/index")['Button']
  Calendar: typeof import("../../app/components/ui/calendar/index")['Calendar']
  CalendarCell: typeof import("../../app/components/ui/calendar/index")['CalendarCell']
  CalendarCellTrigger: typeof import("../../app/components/ui/calendar/index")['CalendarCellTrigger']
  CalendarGrid: typeof import("../../app/components/ui/calendar/index")['CalendarGrid']
  CalendarGridBody: typeof import("../../app/components/ui/calendar/index")['CalendarGridBody']
  CalendarGridHead: typeof import("../../app/components/ui/calendar/index")['CalendarGridHead']
  CalendarGridRow: typeof import("../../app/components/ui/calendar/index")['CalendarGridRow']
  CalendarHeadCell: typeof import("../../app/components/ui/calendar/index")['CalendarHeadCell']
  CalendarHeader: typeof import("../../app/components/ui/calendar/index")['CalendarHeader']
  CalendarHeading: typeof import("../../app/components/ui/calendar/index")['CalendarHeading']
  CalendarNextButton: typeof import("../../app/components/ui/calendar/index")['CalendarNextButton']
  CalendarPrevButton: typeof import("../../app/components/ui/calendar/index")['CalendarPrevButton']
  Card: typeof import("../../app/components/ui/card/index")['Card']
  CardAction: typeof import("../../app/components/ui/card/index")['CardAction']
  CardContent: typeof import("../../app/components/ui/card/index")['CardContent']
  CardDescription: typeof import("../../app/components/ui/card/index")['CardDescription']
  CardFooter: typeof import("../../app/components/ui/card/index")['CardFooter']
  CardHeader: typeof import("../../app/components/ui/card/index")['CardHeader']
  CardTitle: typeof import("../../app/components/ui/card/index")['CardTitle']
  Checkbox: typeof import("../../app/components/ui/checkbox/index")['Checkbox']
  Collapsible: typeof import("../../app/components/ui/collapsible/index")['Collapsible']
  CollapsibleContent: typeof import("../../app/components/ui/collapsible/index")['CollapsibleContent']
  CollapsibleTrigger: typeof import("../../app/components/ui/collapsible/index")['CollapsibleTrigger']
  Dialog: typeof import("../../app/components/ui/dialog/index")['Dialog']
  DialogClose: typeof import("../../app/components/ui/dialog/index")['DialogClose']
  DialogContent: typeof import("../../app/components/ui/dialog/index")['DialogContent']
  DialogDescription: typeof import("../../app/components/ui/dialog/index")['DialogDescription']
  DialogFooter: typeof import("../../app/components/ui/dialog/index")['DialogFooter']
  DialogHeader: typeof import("../../app/components/ui/dialog/index")['DialogHeader']
  DialogOverlay: typeof import("../../app/components/ui/dialog/index")['DialogOverlay']
  DialogScrollContent: typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']
  DialogTitle: typeof import("../../app/components/ui/dialog/index")['DialogTitle']
  DialogTrigger: typeof import("../../app/components/ui/dialog/index")['DialogTrigger']
  DropdownMenu: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']
  DropdownMenuCheckboxItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  DropdownMenuContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
  DropdownMenuGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
  DropdownMenuItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
  DropdownMenuLabel: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
  DropdownMenuRadioGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  DropdownMenuRadioItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  DropdownMenuSeparator: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  DropdownMenuShortcut: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  DropdownMenuSub: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
  DropdownMenuSubContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  DropdownMenuSubTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  DropdownMenuTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  DropdownMenuPortal: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
  Empty: typeof import("../../app/components/ui/empty/index")['Empty']
  EmptyContent: typeof import("../../app/components/ui/empty/index")['EmptyContent']
  EmptyDescription: typeof import("../../app/components/ui/empty/index")['EmptyDescription']
  EmptyHeader: typeof import("../../app/components/ui/empty/index")['EmptyHeader']
  EmptyMedia: typeof import("../../app/components/ui/empty/index")['EmptyMedia']
  EmptyTitle: typeof import("../../app/components/ui/empty/index")['EmptyTitle']
  Field: typeof import("../../app/components/ui/field/index")['Field']
  FieldContent: typeof import("../../app/components/ui/field/index")['FieldContent']
  FieldDescription: typeof import("../../app/components/ui/field/index")['FieldDescription']
  FieldError: typeof import("../../app/components/ui/field/index")['FieldError']
  FieldGroup: typeof import("../../app/components/ui/field/index")['FieldGroup']
  FieldLabel: typeof import("../../app/components/ui/field/index")['FieldLabel']
  FieldLegend: typeof import("../../app/components/ui/field/index")['FieldLegend']
  FieldSeparator: typeof import("../../app/components/ui/field/index")['FieldSeparator']
  FieldSet: typeof import("../../app/components/ui/field/index")['FieldSet']
  FieldTitle: typeof import("../../app/components/ui/field/index")['FieldTitle']
  Input: typeof import("../../app/components/ui/input/index")['Input']
  InputGroup: typeof import("../../app/components/ui/input-group/index")['InputGroup']
  InputGroupAddon: typeof import("../../app/components/ui/input-group/index")['InputGroupAddon']
  InputGroupButton: typeof import("../../app/components/ui/input-group/index")['InputGroupButton']
  InputGroupInput: typeof import("../../app/components/ui/input-group/index")['InputGroupInput']
  InputGroupText: typeof import("../../app/components/ui/input-group/index")['InputGroupText']
  InputGroupTextarea: typeof import("../../app/components/ui/input-group/index")['InputGroupTextarea']
  InputOTP: typeof import("../../app/components/ui/input-otp/index")['InputOTP']
  InputOTPGroup: typeof import("../../app/components/ui/input-otp/index")['InputOTPGroup']
  InputOTPSeparator: typeof import("../../app/components/ui/input-otp/index")['InputOTPSeparator']
  InputOTPSlot: typeof import("../../app/components/ui/input-otp/index")['InputOTPSlot']
  Label: typeof import("../../app/components/ui/label/index")['Label']
  NativeSelect: typeof import("../../app/components/ui/native-select/index")['NativeSelect']
  NativeSelectOptGroup: typeof import("../../app/components/ui/native-select/index")['NativeSelectOptGroup']
  NativeSelectOption: typeof import("../../app/components/ui/native-select/index")['NativeSelectOption']
  Pagination: typeof import("../../app/components/ui/pagination/index")['Pagination']
  PaginationContent: typeof import("../../app/components/ui/pagination/index")['PaginationContent']
  PaginationEllipsis: typeof import("../../app/components/ui/pagination/index")['PaginationEllipsis']
  PaginationFirst: typeof import("../../app/components/ui/pagination/index")['PaginationFirst']
  PaginationItem: typeof import("../../app/components/ui/pagination/index")['PaginationItem']
  PaginationLast: typeof import("../../app/components/ui/pagination/index")['PaginationLast']
  PaginationNext: typeof import("../../app/components/ui/pagination/index")['PaginationNext']
  PaginationPrev: typeof import("../../app/components/ui/pagination/index")['PaginationPrev']
  Select: typeof import("../../app/components/ui/select/index")['Select']
  SelectContent: typeof import("../../app/components/ui/select/index")['SelectContent']
  SelectGroup: typeof import("../../app/components/ui/select/index")['SelectGroup']
  SelectItem: typeof import("../../app/components/ui/select/index")['SelectItem']
  SelectItemText: typeof import("../../app/components/ui/select/index")['SelectItemText']
  SelectLabel: typeof import("../../app/components/ui/select/index")['SelectLabel']
  SelectScrollDownButton: typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']
  SelectScrollUpButton: typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']
  SelectSeparator: typeof import("../../app/components/ui/select/index")['SelectSeparator']
  SelectTrigger: typeof import("../../app/components/ui/select/index")['SelectTrigger']
  SelectValue: typeof import("../../app/components/ui/select/index")['SelectValue']
  Separator: typeof import("../../app/components/ui/separator/index")['Separator']
  Sheet: typeof import("../../app/components/ui/sheet/index")['Sheet']
  SheetClose: typeof import("../../app/components/ui/sheet/index")['SheetClose']
  SheetContent: typeof import("../../app/components/ui/sheet/index")['SheetContent']
  SheetDescription: typeof import("../../app/components/ui/sheet/index")['SheetDescription']
  SheetFooter: typeof import("../../app/components/ui/sheet/index")['SheetFooter']
  SheetHeader: typeof import("../../app/components/ui/sheet/index")['SheetHeader']
  SheetTitle: typeof import("../../app/components/ui/sheet/index")['SheetTitle']
  SheetTrigger: typeof import("../../app/components/ui/sheet/index")['SheetTrigger']
  Sidebar: typeof import("../../app/components/ui/sidebar/index")['Sidebar']
  SidebarContent: typeof import("../../app/components/ui/sidebar/index")['SidebarContent']
  SidebarFooter: typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']
  SidebarGroup: typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']
  SidebarGroupAction: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']
  SidebarGroupContent: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']
  SidebarGroupLabel: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']
  SidebarHeader: typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']
  SidebarInput: typeof import("../../app/components/ui/sidebar/index")['SidebarInput']
  SidebarInset: typeof import("../../app/components/ui/sidebar/index")['SidebarInset']
  SidebarMenu: typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']
  SidebarMenuAction: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']
  SidebarMenuBadge: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']
  SidebarMenuButton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']
  SidebarMenuItem: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']
  SidebarMenuSkeleton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
  SidebarMenuSub: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']
  SidebarMenuSubButton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']
  SidebarMenuSubItem: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']
  SidebarProvider: typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']
  SidebarRail: typeof import("../../app/components/ui/sidebar/index")['SidebarRail']
  SidebarSeparator: typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']
  SidebarTrigger: typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']
  Skeleton: typeof import("../../app/components/ui/skeleton/index")['Skeleton']
  Toaster: typeof import("../../app/components/ui/sonner/index")['Toaster']
  Spinner: typeof import("../../app/components/ui/spinner/index")['Spinner']
  Stepper: typeof import("../../app/components/ui/stepper/index")['Stepper']
  StepperDescription: typeof import("../../app/components/ui/stepper/index")['StepperDescription']
  StepperIndicator: typeof import("../../app/components/ui/stepper/index")['StepperIndicator']
  StepperItem: typeof import("../../app/components/ui/stepper/index")['StepperItem']
  StepperSeparator: typeof import("../../app/components/ui/stepper/index")['StepperSeparator']
  StepperTitle: typeof import("../../app/components/ui/stepper/index")['StepperTitle']
  StepperTrigger: typeof import("../../app/components/ui/stepper/index")['StepperTrigger']
  Switch: typeof import("../../app/components/ui/switch/index")['Switch']
  Table: typeof import("../../app/components/ui/table/index")['Table']
  TableBody: typeof import("../../app/components/ui/table/index")['TableBody']
  TableCaption: typeof import("../../app/components/ui/table/index")['TableCaption']
  TableCell: typeof import("../../app/components/ui/table/index")['TableCell']
  TableEmpty: typeof import("../../app/components/ui/table/index")['TableEmpty']
  TableFooter: typeof import("../../app/components/ui/table/index")['TableFooter']
  TableHead: typeof import("../../app/components/ui/table/index")['TableHead']
  TableHeader: typeof import("../../app/components/ui/table/index")['TableHeader']
  TableRow: typeof import("../../app/components/ui/table/index")['TableRow']
  Tabs: typeof import("../../app/components/ui/tabs/index")['Tabs']
  TabsContent: typeof import("../../app/components/ui/tabs/index")['TabsContent']
  TabsList: typeof import("../../app/components/ui/tabs/index")['TabsList']
  TabsTrigger: typeof import("../../app/components/ui/tabs/index")['TabsTrigger']
  Textarea: typeof import("../../app/components/ui/textarea/index")['Textarea']
  Tooltip: typeof import("../../app/components/ui/tooltip/index")['Tooltip']
  TooltipContent: typeof import("../../app/components/ui/tooltip/index")['TooltipContent']
  TooltipProvider: typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']
  TooltipTrigger: typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']
  ColorScheme: typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']
  Icon: typeof import("../../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_926721a1675078e34d54c6faaaeb929a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAppSpecificAppSidebar: LazyComponent<typeof import("../../app/components/app-specific/AppSidebar.vue")['default']>
  LazyAppSpecificCanVue: LazyComponent<typeof import("../../app/components/app-specific/Can.vue.vue")['default']>
  LazyAppSpecificDragHandle: LazyComponent<typeof import("../../app/components/app-specific/DragHandle.vue")['default']>
  LazyAppSpecificDraggableRow: LazyComponent<typeof import("../../app/components/app-specific/DraggableRow.vue")['default']>
  LazyAppSpecificNavUser: LazyComponent<typeof import("../../app/components/app-specific/NavUser.vue")['default']>
  LazyAppSpecificToastContainer: LazyComponent<typeof import("../../app/components/app-specific/Toast/toastContainer.vue")['default']>
  LazyAppSpecificComponentsAmmunitionTypesTab: LazyComponent<typeof import("../../app/components/app-specific/components/AmmunitionTypesTab.vue")['default']>
  LazyAppSpecificComponentsArmoryTab: LazyComponent<typeof import("../../app/components/app-specific/components/ArmoryTab.vue")['default']>
  LazyAppSpecificComponentsFirearmsTab: LazyComponent<typeof import("../../app/components/app-specific/components/FirearmsTab.vue")['default']>
  LazyAppSpecificComponentsPendingApprovalTab: LazyComponent<typeof import("../../app/components/app-specific/components/PendingApprovalTab.vue")['default']>
  LazyAppSpecificDialogsConfirmationDialog: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ConfirmationDialog.vue")['default']>
  LazyAppSpecificDialogsTransferConfirmationDialog: LazyComponent<typeof import("../../app/components/app-specific/dialogs/TransferConfirmationDialog.vue")['default']>
  LazyAppSpecificDialogsAmmunitionAddAmmoInventory: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ammunition/AddAmmoInventory.vue")['default']>
  LazyAppSpecificDialogsAmmunitionAdjustInventory: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ammunition/AdjustInventory.vue")['default']>
  LazyAppSpecificDialogsAmmunitionDetails: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ammunition/AmmunitionDetails.vue")['default']>
  LazyAppSpecificDialogsAmmunitionModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ammunition/AmmunitionModal.vue")['default']>
  LazyAppSpecificDialogsAmmunitionTypeModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ammunition/AmmunitionTypeModal.vue")['default']>
  LazyAppSpecificDialogsAmmunitionRegisterAmmoType: LazyComponent<typeof import("../../app/components/app-specific/dialogs/ammunition/RegisterAmmoType.vue")['default']>
  LazyAppSpecificDialogsArmsregisterCreateArmoryModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/armsregister/CreateArmoryModal.vue")['default']>
  LazyAppSpecificDialogsArmsregisterDisposeFireArm: LazyComponent<typeof import("../../app/components/app-specific/dialogs/armsregister/DisposeFireArm.vue")['default']>
  LazyAppSpecificDialogsArmsregisterFireArmsDetails: LazyComponent<typeof import("../../app/components/app-specific/dialogs/armsregister/FireArmsDetails.vue")['default']>
  LazyAppSpecificDialogsArmsregisterRecordFireArm: LazyComponent<typeof import("../../app/components/app-specific/dialogs/armsregister/RecordFireArm.vue")['default']>
  LazyAppSpecificDialogsArmsregisterRegisterFireArm: LazyComponent<typeof import("../../app/components/app-specific/dialogs/armsregister/RegisterFireArm.vue")['default']>
  LazyAppSpecificDialogsArmsregisterReviewFireArm: LazyComponent<typeof import("../../app/components/app-specific/dialogs/armsregister/ReviewFireArm.vue")['default']>
  LazyAppSpecificDialogsBranchModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/BranchModal.vue")['default']>
  LazyAppSpecificDialogsFirearmIssueFireArm: LazyComponent<typeof import("../../app/components/app-specific/dialogs/firearm/IssueFireArm.vue")['default']>
  LazyAppSpecificDialogsFirearmReturnFireArm: LazyComponent<typeof import("../../app/components/app-specific/dialogs/firearm/ReturnFireArm.vue")['default']>
  LazyAppSpecificDialogsLocationModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/location/LocationModal.vue")['default']>
  LazyAppSpecificDialogsRolesRoleModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/roles/RoleModal.vue")['default']>
  LazyAppSpecificDialogsSecuritydevicesDeviceDetails: LazyComponent<typeof import("../../app/components/app-specific/dialogs/securitydevices/DeviceDetails.vue")['default']>
  LazyAppSpecificDialogsSecuritydevicesDeviceInspection: LazyComponent<typeof import("../../app/components/app-specific/dialogs/securitydevices/DeviceInspection.vue")['default']>
  LazyAppSpecificDialogsSecuritydevicesSecurityDeviceModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/securitydevices/SecurityDeviceModal.vue")['default']>
  LazyAppSpecificDialogsUsersAddEdit: LazyComponent<typeof import("../../app/components/app-specific/dialogs/users/AddEdit.vue")['default']>
  LazyAppSpecificDialogsUsersInfoField: LazyComponent<typeof import("../../app/components/app-specific/dialogs/users/InfoField.vue")['default']>
  LazyAppSpecificDialogsUsersUserDetails: LazyComponent<typeof import("../../app/components/app-specific/dialogs/users/UserDetails.vue")['default']>
  LazyAppSpecificDialogsUsersUserModal: LazyComponent<typeof import("../../app/components/app-specific/dialogs/users/UserModal.vue")['default']>
  LazyAppSpecificFormsAllocationForm: LazyComponent<typeof import("../../app/components/app-specific/forms/AllocationForm.vue")['default']>
  LazyAppSpecificFormsAmmunitionForm: LazyComponent<typeof import("../../app/components/app-specific/forms/AmmunitionForm.vue")['default']>
  LazyAppSpecificFormsCreateIssuanceForm: LazyComponent<typeof import("../../app/components/app-specific/forms/CreateIssuanceForm.vue")['default']>
  LazyAppSpecificFormsFireArmForm: LazyComponent<typeof import("../../app/components/app-specific/forms/FireArmForm.vue")['default']>
  LazyAppSpecificFormsFirearmReturnDialog: LazyComponent<typeof import("../../app/components/app-specific/forms/FirearmReturnDialog.vue")['default']>
  LazyAppSpecificFormsLoginForm: LazyComponent<typeof import("../../app/components/app-specific/forms/LoginForm.vue")['default']>
  LazyAppSpecificFormsRoleForm: LazyComponent<typeof import("../../app/components/app-specific/forms/RoleForm.vue")['default']>
  LazyAppSpecificFormsSetupBranchForm: LazyComponent<typeof import("../../app/components/app-specific/forms/SetupBranchForm.vue")['default']>
  LazyAppSpecificFormsUserForm: LazyComponent<typeof import("../../app/components/app-specific/forms/UserForm.vue")['default']>
  LazyAppSpecificPartialPageAmmunitions: LazyComponent<typeof import("../../app/components/app-specific/partial-page/ammunitions.vue")['default']>
  LazyAppSpecificPartialPageFirearms: LazyComponent<typeof import("../../app/components/app-specific/partial-page/firearms.vue")['default']>
  LazyAppSpecificPartialPageKits: LazyComponent<typeof import("../../app/components/app-specific/partial-page/kits.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyAccordion: LazyComponent<typeof import("../../app/components/ui/accordion/index")['Accordion']>
  LazyAccordionContent: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionContent']>
  LazyAccordionItem: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionItem']>
  LazyAccordionTrigger: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']>
  LazyAlert: LazyComponent<typeof import("../../app/components/ui/alert/index")['Alert']>
  LazyAlertDescription: LazyComponent<typeof import("../../app/components/ui/alert/index")['AlertDescription']>
  LazyAlertTitle: LazyComponent<typeof import("../../app/components/ui/alert/index")['AlertTitle']>
  LazyAlertDialog: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']>
  LazyAlertDialogAction: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']>
  LazyAlertDialogCancel: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
  LazyAlertDialogContent: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']>
  LazyAlertDialogDescription: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
  LazyAlertDialogFooter: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
  LazyAlertDialogHeader: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
  LazyAlertDialogTitle: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
  LazyAlertDialogTrigger: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
  LazyAvatar: LazyComponent<typeof import("../../app/components/ui/avatar/index")['Avatar']>
  LazyAvatarFallback: LazyComponent<typeof import("../../app/components/ui/avatar/index")['AvatarFallback']>
  LazyAvatarImage: LazyComponent<typeof import("../../app/components/ui/avatar/index")['AvatarImage']>
  LazyBadge: LazyComponent<typeof import("../../app/components/ui/badge/index")['Badge']>
  LazyBreadcrumb: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['Breadcrumb']>
  LazyBreadcrumbEllipsis: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
  LazyBreadcrumbItem: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbItem']>
  LazyBreadcrumbLink: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbLink']>
  LazyBreadcrumbList: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbList']>
  LazyBreadcrumbPage: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbPage']>
  LazyBreadcrumbSeparator: LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']>
  LazyButton: LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
  LazyCalendar: LazyComponent<typeof import("../../app/components/ui/calendar/index")['Calendar']>
  LazyCalendarCell: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarCell']>
  LazyCalendarCellTrigger: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarCellTrigger']>
  LazyCalendarGrid: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGrid']>
  LazyCalendarGridBody: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridBody']>
  LazyCalendarGridHead: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridHead']>
  LazyCalendarGridRow: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridRow']>
  LazyCalendarHeadCell: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeadCell']>
  LazyCalendarHeader: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeader']>
  LazyCalendarHeading: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeading']>
  LazyCalendarNextButton: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarNextButton']>
  LazyCalendarPrevButton: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarPrevButton']>
  LazyCard: LazyComponent<typeof import("../../app/components/ui/card/index")['Card']>
  LazyCardAction: LazyComponent<typeof import("../../app/components/ui/card/index")['CardAction']>
  LazyCardContent: LazyComponent<typeof import("../../app/components/ui/card/index")['CardContent']>
  LazyCardDescription: LazyComponent<typeof import("../../app/components/ui/card/index")['CardDescription']>
  LazyCardFooter: LazyComponent<typeof import("../../app/components/ui/card/index")['CardFooter']>
  LazyCardHeader: LazyComponent<typeof import("../../app/components/ui/card/index")['CardHeader']>
  LazyCardTitle: LazyComponent<typeof import("../../app/components/ui/card/index")['CardTitle']>
  LazyCheckbox: LazyComponent<typeof import("../../app/components/ui/checkbox/index")['Checkbox']>
  LazyCollapsible: LazyComponent<typeof import("../../app/components/ui/collapsible/index")['Collapsible']>
  LazyCollapsibleContent: LazyComponent<typeof import("../../app/components/ui/collapsible/index")['CollapsibleContent']>
  LazyCollapsibleTrigger: LazyComponent<typeof import("../../app/components/ui/collapsible/index")['CollapsibleTrigger']>
  LazyDialog: LazyComponent<typeof import("../../app/components/ui/dialog/index")['Dialog']>
  LazyDialogClose: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogClose']>
  LazyDialogContent: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogContent']>
  LazyDialogDescription: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogDescription']>
  LazyDialogFooter: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogFooter']>
  LazyDialogHeader: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogHeader']>
  LazyDialogOverlay: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogOverlay']>
  LazyDialogScrollContent: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']>
  LazyDialogTitle: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTitle']>
  LazyDialogTrigger: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTrigger']>
  LazyDropdownMenu: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']>
  LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  LazyDropdownMenuContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
  LazyDropdownMenuGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  LazyDropdownMenuItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
  LazyDropdownMenuLabel: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  LazyDropdownMenuRadioItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  LazyDropdownMenuSeparator: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  LazyDropdownMenuShortcut: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  LazyDropdownMenuSub: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
  LazyDropdownMenuSubContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  LazyDropdownMenuTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  LazyDropdownMenuPortal: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  LazyEmpty: LazyComponent<typeof import("../../app/components/ui/empty/index")['Empty']>
  LazyEmptyContent: LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyContent']>
  LazyEmptyDescription: LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyDescription']>
  LazyEmptyHeader: LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyHeader']>
  LazyEmptyMedia: LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyMedia']>
  LazyEmptyTitle: LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyTitle']>
  LazyField: LazyComponent<typeof import("../../app/components/ui/field/index")['Field']>
  LazyFieldContent: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldContent']>
  LazyFieldDescription: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldDescription']>
  LazyFieldError: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldError']>
  LazyFieldGroup: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldGroup']>
  LazyFieldLabel: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldLabel']>
  LazyFieldLegend: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldLegend']>
  LazyFieldSeparator: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldSeparator']>
  LazyFieldSet: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldSet']>
  LazyFieldTitle: LazyComponent<typeof import("../../app/components/ui/field/index")['FieldTitle']>
  LazyInput: LazyComponent<typeof import("../../app/components/ui/input/index")['Input']>
  LazyInputGroup: LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroup']>
  LazyInputGroupAddon: LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupAddon']>
  LazyInputGroupButton: LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupButton']>
  LazyInputGroupInput: LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupInput']>
  LazyInputGroupText: LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupText']>
  LazyInputGroupTextarea: LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupTextarea']>
  LazyInputOTP: LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTP']>
  LazyInputOTPGroup: LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTPGroup']>
  LazyInputOTPSeparator: LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTPSeparator']>
  LazyInputOTPSlot: LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTPSlot']>
  LazyLabel: LazyComponent<typeof import("../../app/components/ui/label/index")['Label']>
  LazyNativeSelect: LazyComponent<typeof import("../../app/components/ui/native-select/index")['NativeSelect']>
  LazyNativeSelectOptGroup: LazyComponent<typeof import("../../app/components/ui/native-select/index")['NativeSelectOptGroup']>
  LazyNativeSelectOption: LazyComponent<typeof import("../../app/components/ui/native-select/index")['NativeSelectOption']>
  LazyPagination: LazyComponent<typeof import("../../app/components/ui/pagination/index")['Pagination']>
  LazyPaginationContent: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationContent']>
  LazyPaginationEllipsis: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationEllipsis']>
  LazyPaginationFirst: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationFirst']>
  LazyPaginationItem: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationItem']>
  LazyPaginationLast: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationLast']>
  LazyPaginationNext: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationNext']>
  LazyPaginationPrev: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationPrev']>
  LazySelect: LazyComponent<typeof import("../../app/components/ui/select/index")['Select']>
  LazySelectContent: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectContent']>
  LazySelectGroup: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectGroup']>
  LazySelectItem: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItem']>
  LazySelectItemText: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItemText']>
  LazySelectLabel: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectLabel']>
  LazySelectScrollDownButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']>
  LazySelectScrollUpButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']>
  LazySelectSeparator: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectSeparator']>
  LazySelectTrigger: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectTrigger']>
  LazySelectValue: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectValue']>
  LazySeparator: LazyComponent<typeof import("../../app/components/ui/separator/index")['Separator']>
  LazySheet: LazyComponent<typeof import("../../app/components/ui/sheet/index")['Sheet']>
  LazySheetClose: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetClose']>
  LazySheetContent: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetContent']>
  LazySheetDescription: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetDescription']>
  LazySheetFooter: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetFooter']>
  LazySheetHeader: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetHeader']>
  LazySheetTitle: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTitle']>
  LazySheetTrigger: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTrigger']>
  LazySidebar: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['Sidebar']>
  LazySidebarContent: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarContent']>
  LazySidebarFooter: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']>
  LazySidebarGroup: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']>
  LazySidebarGroupAction: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']>
  LazySidebarGroupContent: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']>
  LazySidebarGroupLabel: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']>
  LazySidebarHeader: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']>
  LazySidebarInput: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInput']>
  LazySidebarInset: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInset']>
  LazySidebarMenu: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']>
  LazySidebarMenuAction: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']>
  LazySidebarMenuBadge: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']>
  LazySidebarMenuButton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']>
  LazySidebarMenuItem: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']>
  LazySidebarMenuSkeleton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
  LazySidebarMenuSub: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']>
  LazySidebarMenuSubButton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
  LazySidebarMenuSubItem: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
  LazySidebarProvider: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']>
  LazySidebarRail: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarRail']>
  LazySidebarSeparator: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']>
  LazySidebarTrigger: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']>
  LazySkeleton: LazyComponent<typeof import("../../app/components/ui/skeleton/index")['Skeleton']>
  LazyToaster: LazyComponent<typeof import("../../app/components/ui/sonner/index")['Toaster']>
  LazySpinner: LazyComponent<typeof import("../../app/components/ui/spinner/index")['Spinner']>
  LazyStepper: LazyComponent<typeof import("../../app/components/ui/stepper/index")['Stepper']>
  LazyStepperDescription: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperDescription']>
  LazyStepperIndicator: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperIndicator']>
  LazyStepperItem: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperItem']>
  LazyStepperSeparator: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperSeparator']>
  LazyStepperTitle: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperTitle']>
  LazyStepperTrigger: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperTrigger']>
  LazySwitch: LazyComponent<typeof import("../../app/components/ui/switch/index")['Switch']>
  LazyTable: LazyComponent<typeof import("../../app/components/ui/table/index")['Table']>
  LazyTableBody: LazyComponent<typeof import("../../app/components/ui/table/index")['TableBody']>
  LazyTableCaption: LazyComponent<typeof import("../../app/components/ui/table/index")['TableCaption']>
  LazyTableCell: LazyComponent<typeof import("../../app/components/ui/table/index")['TableCell']>
  LazyTableEmpty: LazyComponent<typeof import("../../app/components/ui/table/index")['TableEmpty']>
  LazyTableFooter: LazyComponent<typeof import("../../app/components/ui/table/index")['TableFooter']>
  LazyTableHead: LazyComponent<typeof import("../../app/components/ui/table/index")['TableHead']>
  LazyTableHeader: LazyComponent<typeof import("../../app/components/ui/table/index")['TableHeader']>
  LazyTableRow: LazyComponent<typeof import("../../app/components/ui/table/index")['TableRow']>
  LazyTabs: LazyComponent<typeof import("../../app/components/ui/tabs/index")['Tabs']>
  LazyTabsContent: LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsContent']>
  LazyTabsList: LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsList']>
  LazyTabsTrigger: LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsTrigger']>
  LazyTextarea: LazyComponent<typeof import("../../app/components/ui/textarea/index")['Textarea']>
  LazyTooltip: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['Tooltip']>
  LazyTooltipContent: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipContent']>
  LazyTooltipProvider: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']>
  LazyTooltipTrigger: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']>
  LazyColorScheme: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']>
  LazyIcon: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_926721a1675078e34d54c6faaaeb929a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
