
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppSpecificAppSidebar: typeof import("../app/components/app-specific/AppSidebar.vue")['default']
export const AppSpecificCanVue: typeof import("../app/components/app-specific/Can.vue.vue")['default']
export const AppSpecificDragHandle: typeof import("../app/components/app-specific/DragHandle.vue")['default']
export const AppSpecificDraggableRow: typeof import("../app/components/app-specific/DraggableRow.vue")['default']
export const AppSpecificNavUser: typeof import("../app/components/app-specific/NavUser.vue")['default']
export const AppSpecificToastContainer: typeof import("../app/components/app-specific/Toast/toastContainer.vue")['default']
export const AppSpecificComponentsAmmunitionTypesTab: typeof import("../app/components/app-specific/components/AmmunitionTypesTab.vue")['default']
export const AppSpecificComponentsArmoryTab: typeof import("../app/components/app-specific/components/ArmoryTab.vue")['default']
export const AppSpecificComponentsFirearmsTab: typeof import("../app/components/app-specific/components/FirearmsTab.vue")['default']
export const AppSpecificComponentsPendingApprovalTab: typeof import("../app/components/app-specific/components/PendingApprovalTab.vue")['default']
export const AppSpecificDialogsConfirmationDialog: typeof import("../app/components/app-specific/dialogs/ConfirmationDialog.vue")['default']
export const AppSpecificDialogsTransferConfirmationDialog: typeof import("../app/components/app-specific/dialogs/TransferConfirmationDialog.vue")['default']
export const AppSpecificDialogsAmmunitionAddAmmoInventory: typeof import("../app/components/app-specific/dialogs/ammunition/AddAmmoInventory.vue")['default']
export const AppSpecificDialogsAmmunitionAdjustInventory: typeof import("../app/components/app-specific/dialogs/ammunition/AdjustInventory.vue")['default']
export const AppSpecificDialogsAmmunitionDetails: typeof import("../app/components/app-specific/dialogs/ammunition/AmmunitionDetails.vue")['default']
export const AppSpecificDialogsAmmunitionModal: typeof import("../app/components/app-specific/dialogs/ammunition/AmmunitionModal.vue")['default']
export const AppSpecificDialogsAmmunitionTypeModal: typeof import("../app/components/app-specific/dialogs/ammunition/AmmunitionTypeModal.vue")['default']
export const AppSpecificDialogsAmmunitionRegisterAmmoType: typeof import("../app/components/app-specific/dialogs/ammunition/RegisterAmmoType.vue")['default']
export const AppSpecificDialogsArmsregisterCreateArmoryModal: typeof import("../app/components/app-specific/dialogs/armsregister/CreateArmoryModal.vue")['default']
export const AppSpecificDialogsArmsregisterDisposeFireArm: typeof import("../app/components/app-specific/dialogs/armsregister/DisposeFireArm.vue")['default']
export const AppSpecificDialogsArmsregisterFireArmsDetails: typeof import("../app/components/app-specific/dialogs/armsregister/FireArmsDetails.vue")['default']
export const AppSpecificDialogsArmsregisterRecordFireArm: typeof import("../app/components/app-specific/dialogs/armsregister/RecordFireArm.vue")['default']
export const AppSpecificDialogsArmsregisterRegisterFireArm: typeof import("../app/components/app-specific/dialogs/armsregister/RegisterFireArm.vue")['default']
export const AppSpecificDialogsArmsregisterReviewFireArm: typeof import("../app/components/app-specific/dialogs/armsregister/ReviewFireArm.vue")['default']
export const AppSpecificDialogsBranchModal: typeof import("../app/components/app-specific/dialogs/branch/BranchModal.vue")['default']
export const AppSpecificDialogsFirearmIssueFireArm: typeof import("../app/components/app-specific/dialogs/firearm/IssueFireArm.vue")['default']
export const AppSpecificDialogsFirearmReturnFireArm: typeof import("../app/components/app-specific/dialogs/firearm/ReturnFireArm.vue")['default']
export const AppSpecificDialogsLocationModal: typeof import("../app/components/app-specific/dialogs/location/LocationModal.vue")['default']
export const AppSpecificDialogsRolesRoleModal: typeof import("../app/components/app-specific/dialogs/roles/RoleModal.vue")['default']
export const AppSpecificDialogsSecuritydevicesDeviceDetails: typeof import("../app/components/app-specific/dialogs/securitydevices/DeviceDetails.vue")['default']
export const AppSpecificDialogsSecuritydevicesDeviceInspection: typeof import("../app/components/app-specific/dialogs/securitydevices/DeviceInspection.vue")['default']
export const AppSpecificDialogsSecuritydevicesSecurityDeviceModal: typeof import("../app/components/app-specific/dialogs/securitydevices/SecurityDeviceModal.vue")['default']
export const AppSpecificDialogsUsersAddEdit: typeof import("../app/components/app-specific/dialogs/users/AddEdit.vue")['default']
export const AppSpecificDialogsUsersInfoField: typeof import("../app/components/app-specific/dialogs/users/InfoField.vue")['default']
export const AppSpecificDialogsUsersUserDetails: typeof import("../app/components/app-specific/dialogs/users/UserDetails.vue")['default']
export const AppSpecificDialogsUsersUserModal: typeof import("../app/components/app-specific/dialogs/users/UserModal.vue")['default']
export const AppSpecificFormsAllocationForm: typeof import("../app/components/app-specific/forms/AllocationForm.vue")['default']
export const AppSpecificFormsAmmunitionForm: typeof import("../app/components/app-specific/forms/AmmunitionForm.vue")['default']
export const AppSpecificFormsCreateIssuanceForm: typeof import("../app/components/app-specific/forms/CreateIssuanceForm.vue")['default']
export const AppSpecificFormsFireArmForm: typeof import("../app/components/app-specific/forms/FireArmForm.vue")['default']
export const AppSpecificFormsFirearmReturnDialog: typeof import("../app/components/app-specific/forms/FirearmReturnDialog.vue")['default']
export const AppSpecificFormsLoginForm: typeof import("../app/components/app-specific/forms/LoginForm.vue")['default']
export const AppSpecificFormsRoleForm: typeof import("../app/components/app-specific/forms/RoleForm.vue")['default']
export const AppSpecificFormsSetupBranchForm: typeof import("../app/components/app-specific/forms/SetupBranchForm.vue")['default']
export const AppSpecificFormsUserForm: typeof import("../app/components/app-specific/forms/UserForm.vue")['default']
export const AppSpecificPartialPageAmmunitions: typeof import("../app/components/app-specific/partial-page/ammunitions.vue")['default']
export const AppSpecificPartialPageFirearms: typeof import("../app/components/app-specific/partial-page/firearms.vue")['default']
export const AppSpecificPartialPageKits: typeof import("../app/components/app-specific/partial-page/kits.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Accordion: typeof import("../app/components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../app/components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../app/components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../app/components/ui/accordion/index")['AccordionTrigger']
export const Alert: typeof import("../app/components/ui/alert/index")['Alert']
export const AlertDescription: typeof import("../app/components/ui/alert/index")['AlertDescription']
export const AlertTitle: typeof import("../app/components/ui/alert/index")['AlertTitle']
export const AlertDialog: typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogAction: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']
export const AlertDialogContent: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogDescription: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogHeader: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogTrigger: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
export const Avatar: typeof import("../app/components/ui/avatar/index")['Avatar']
export const AvatarFallback: typeof import("../app/components/ui/avatar/index")['AvatarFallback']
export const AvatarImage: typeof import("../app/components/ui/avatar/index")['AvatarImage']
export const Badge: typeof import("../app/components/ui/badge/index")['Badge']
export const Breadcrumb: typeof import("../app/components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../app/components/ui/button/index")['Button']
export const Calendar: typeof import("../app/components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../app/components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../app/components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../app/components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../app/components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../app/components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../app/components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../app/components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../app/components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../app/components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../app/components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../app/components/ui/calendar/index")['CalendarPrevButton']
export const Card: typeof import("../app/components/ui/card/index")['Card']
export const CardAction: typeof import("../app/components/ui/card/index")['CardAction']
export const CardContent: typeof import("../app/components/ui/card/index")['CardContent']
export const CardDescription: typeof import("../app/components/ui/card/index")['CardDescription']
export const CardFooter: typeof import("../app/components/ui/card/index")['CardFooter']
export const CardHeader: typeof import("../app/components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../app/components/ui/card/index")['CardTitle']
export const Checkbox: typeof import("../app/components/ui/checkbox/index")['Checkbox']
export const Collapsible: typeof import("../app/components/ui/collapsible/index")['Collapsible']
export const CollapsibleContent: typeof import("../app/components/ui/collapsible/index")['CollapsibleContent']
export const CollapsibleTrigger: typeof import("../app/components/ui/collapsible/index")['CollapsibleTrigger']
export const Dialog: typeof import("../app/components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../app/components/ui/dialog/index")['DialogClose']
export const DialogContent: typeof import("../app/components/ui/dialog/index")['DialogContent']
export const DialogDescription: typeof import("../app/components/ui/dialog/index")['DialogDescription']
export const DialogFooter: typeof import("../app/components/ui/dialog/index")['DialogFooter']
export const DialogHeader: typeof import("../app/components/ui/dialog/index")['DialogHeader']
export const DialogOverlay: typeof import("../app/components/ui/dialog/index")['DialogOverlay']
export const DialogScrollContent: typeof import("../app/components/ui/dialog/index")['DialogScrollContent']
export const DialogTitle: typeof import("../app/components/ui/dialog/index")['DialogTitle']
export const DialogTrigger: typeof import("../app/components/ui/dialog/index")['DialogTrigger']
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Empty: typeof import("../app/components/ui/empty/index")['Empty']
export const EmptyContent: typeof import("../app/components/ui/empty/index")['EmptyContent']
export const EmptyDescription: typeof import("../app/components/ui/empty/index")['EmptyDescription']
export const EmptyHeader: typeof import("../app/components/ui/empty/index")['EmptyHeader']
export const EmptyMedia: typeof import("../app/components/ui/empty/index")['EmptyMedia']
export const EmptyTitle: typeof import("../app/components/ui/empty/index")['EmptyTitle']
export const Field: typeof import("../app/components/ui/field/index")['Field']
export const FieldContent: typeof import("../app/components/ui/field/index")['FieldContent']
export const FieldDescription: typeof import("../app/components/ui/field/index")['FieldDescription']
export const FieldError: typeof import("../app/components/ui/field/index")['FieldError']
export const FieldGroup: typeof import("../app/components/ui/field/index")['FieldGroup']
export const FieldLabel: typeof import("../app/components/ui/field/index")['FieldLabel']
export const FieldLegend: typeof import("../app/components/ui/field/index")['FieldLegend']
export const FieldSeparator: typeof import("../app/components/ui/field/index")['FieldSeparator']
export const FieldSet: typeof import("../app/components/ui/field/index")['FieldSet']
export const FieldTitle: typeof import("../app/components/ui/field/index")['FieldTitle']
export const Input: typeof import("../app/components/ui/input/index")['Input']
export const InputGroup: typeof import("../app/components/ui/input-group/index")['InputGroup']
export const InputGroupAddon: typeof import("../app/components/ui/input-group/index")['InputGroupAddon']
export const InputGroupButton: typeof import("../app/components/ui/input-group/index")['InputGroupButton']
export const InputGroupInput: typeof import("../app/components/ui/input-group/index")['InputGroupInput']
export const InputGroupText: typeof import("../app/components/ui/input-group/index")['InputGroupText']
export const InputGroupTextarea: typeof import("../app/components/ui/input-group/index")['InputGroupTextarea']
export const InputOTP: typeof import("../app/components/ui/input-otp/index")['InputOTP']
export const InputOTPGroup: typeof import("../app/components/ui/input-otp/index")['InputOTPGroup']
export const InputOTPSeparator: typeof import("../app/components/ui/input-otp/index")['InputOTPSeparator']
export const InputOTPSlot: typeof import("../app/components/ui/input-otp/index")['InputOTPSlot']
export const Label: typeof import("../app/components/ui/label/index")['Label']
export const NativeSelect: typeof import("../app/components/ui/native-select/index")['NativeSelect']
export const NativeSelectOptGroup: typeof import("../app/components/ui/native-select/index")['NativeSelectOptGroup']
export const NativeSelectOption: typeof import("../app/components/ui/native-select/index")['NativeSelectOption']
export const Pagination: typeof import("../app/components/ui/pagination/index")['Pagination']
export const PaginationContent: typeof import("../app/components/ui/pagination/index")['PaginationContent']
export const PaginationEllipsis: typeof import("../app/components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../app/components/ui/pagination/index")['PaginationFirst']
export const PaginationItem: typeof import("../app/components/ui/pagination/index")['PaginationItem']
export const PaginationLast: typeof import("../app/components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../app/components/ui/pagination/index")['PaginationNext']
export const PaginationPrev: typeof import("../app/components/ui/pagination/index")['PaginationPrev']
export const Select: typeof import("../app/components/ui/select/index")['Select']
export const SelectContent: typeof import("../app/components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../app/components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../app/components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../app/components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../app/components/ui/select/index")['SelectLabel']
export const SelectScrollDownButton: typeof import("../app/components/ui/select/index")['SelectScrollDownButton']
export const SelectScrollUpButton: typeof import("../app/components/ui/select/index")['SelectScrollUpButton']
export const SelectSeparator: typeof import("../app/components/ui/select/index")['SelectSeparator']
export const SelectTrigger: typeof import("../app/components/ui/select/index")['SelectTrigger']
export const SelectValue: typeof import("../app/components/ui/select/index")['SelectValue']
export const Separator: typeof import("../app/components/ui/separator/index")['Separator']
export const Sheet: typeof import("../app/components/ui/sheet/index")['Sheet']
export const SheetClose: typeof import("../app/components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../app/components/ui/sheet/index")['SheetContent']
export const SheetDescription: typeof import("../app/components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../app/components/ui/sheet/index")['SheetFooter']
export const SheetHeader: typeof import("../app/components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../app/components/ui/sheet/index")['SheetTitle']
export const SheetTrigger: typeof import("../app/components/ui/sheet/index")['SheetTrigger']
export const Sidebar: typeof import("../app/components/ui/sidebar/index")['Sidebar']
export const SidebarContent: typeof import("../app/components/ui/sidebar/index")['SidebarContent']
export const SidebarFooter: typeof import("../app/components/ui/sidebar/index")['SidebarFooter']
export const SidebarGroup: typeof import("../app/components/ui/sidebar/index")['SidebarGroup']
export const SidebarGroupAction: typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']
export const SidebarGroupContent: typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']
export const SidebarGroupLabel: typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']
export const SidebarHeader: typeof import("../app/components/ui/sidebar/index")['SidebarHeader']
export const SidebarInput: typeof import("../app/components/ui/sidebar/index")['SidebarInput']
export const SidebarInset: typeof import("../app/components/ui/sidebar/index")['SidebarInset']
export const SidebarMenu: typeof import("../app/components/ui/sidebar/index")['SidebarMenu']
export const SidebarMenuAction: typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']
export const SidebarMenuBadge: typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']
export const SidebarMenuButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']
export const SidebarMenuItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']
export const SidebarMenuSkeleton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
export const SidebarMenuSub: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']
export const SidebarMenuSubButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']
export const SidebarMenuSubItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']
export const SidebarProvider: typeof import("../app/components/ui/sidebar/index")['SidebarProvider']
export const SidebarRail: typeof import("../app/components/ui/sidebar/index")['SidebarRail']
export const SidebarSeparator: typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']
export const SidebarTrigger: typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']
export const Skeleton: typeof import("../app/components/ui/skeleton/index")['Skeleton']
export const Toaster: typeof import("../app/components/ui/sonner/index")['Toaster']
export const Spinner: typeof import("../app/components/ui/spinner/index")['Spinner']
export const Stepper: typeof import("../app/components/ui/stepper/index")['Stepper']
export const StepperDescription: typeof import("../app/components/ui/stepper/index")['StepperDescription']
export const StepperIndicator: typeof import("../app/components/ui/stepper/index")['StepperIndicator']
export const StepperItem: typeof import("../app/components/ui/stepper/index")['StepperItem']
export const StepperSeparator: typeof import("../app/components/ui/stepper/index")['StepperSeparator']
export const StepperTitle: typeof import("../app/components/ui/stepper/index")['StepperTitle']
export const StepperTrigger: typeof import("../app/components/ui/stepper/index")['StepperTrigger']
export const Switch: typeof import("../app/components/ui/switch/index")['Switch']
export const Table: typeof import("../app/components/ui/table/index")['Table']
export const TableBody: typeof import("../app/components/ui/table/index")['TableBody']
export const TableCaption: typeof import("../app/components/ui/table/index")['TableCaption']
export const TableCell: typeof import("../app/components/ui/table/index")['TableCell']
export const TableEmpty: typeof import("../app/components/ui/table/index")['TableEmpty']
export const TableFooter: typeof import("../app/components/ui/table/index")['TableFooter']
export const TableHead: typeof import("../app/components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../app/components/ui/table/index")['TableHeader']
export const TableRow: typeof import("../app/components/ui/table/index")['TableRow']
export const Tabs: typeof import("../app/components/ui/tabs/index")['Tabs']
export const TabsContent: typeof import("../app/components/ui/tabs/index")['TabsContent']
export const TabsList: typeof import("../app/components/ui/tabs/index")['TabsList']
export const TabsTrigger: typeof import("../app/components/ui/tabs/index")['TabsTrigger']
export const Textarea: typeof import("../app/components/ui/textarea/index")['Textarea']
export const Tooltip: typeof import("../app/components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../app/components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../app/components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']
export const Icon: typeof import("../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_926721a1675078e34d54c6faaaeb929a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppSpecificAppSidebar: LazyComponent<typeof import("../app/components/app-specific/AppSidebar.vue")['default']>
export const LazyAppSpecificCanVue: LazyComponent<typeof import("../app/components/app-specific/Can.vue.vue")['default']>
export const LazyAppSpecificDragHandle: LazyComponent<typeof import("../app/components/app-specific/DragHandle.vue")['default']>
export const LazyAppSpecificDraggableRow: LazyComponent<typeof import("../app/components/app-specific/DraggableRow.vue")['default']>
export const LazyAppSpecificNavUser: LazyComponent<typeof import("../app/components/app-specific/NavUser.vue")['default']>
export const LazyAppSpecificToastContainer: LazyComponent<typeof import("../app/components/app-specific/Toast/toastContainer.vue")['default']>
export const LazyAppSpecificComponentsAmmunitionTypesTab: LazyComponent<typeof import("../app/components/app-specific/components/AmmunitionTypesTab.vue")['default']>
export const LazyAppSpecificComponentsArmoryTab: LazyComponent<typeof import("../app/components/app-specific/components/ArmoryTab.vue")['default']>
export const LazyAppSpecificComponentsFirearmsTab: LazyComponent<typeof import("../app/components/app-specific/components/FirearmsTab.vue")['default']>
export const LazyAppSpecificComponentsPendingApprovalTab: LazyComponent<typeof import("../app/components/app-specific/components/PendingApprovalTab.vue")['default']>
export const LazyAppSpecificDialogsConfirmationDialog: LazyComponent<typeof import("../app/components/app-specific/dialogs/ConfirmationDialog.vue")['default']>
export const LazyAppSpecificDialogsTransferConfirmationDialog: LazyComponent<typeof import("../app/components/app-specific/dialogs/TransferConfirmationDialog.vue")['default']>
export const LazyAppSpecificDialogsAmmunitionAddAmmoInventory: LazyComponent<typeof import("../app/components/app-specific/dialogs/ammunition/AddAmmoInventory.vue")['default']>
export const LazyAppSpecificDialogsAmmunitionAdjustInventory: LazyComponent<typeof import("../app/components/app-specific/dialogs/ammunition/AdjustInventory.vue")['default']>
export const LazyAppSpecificDialogsAmmunitionDetails: LazyComponent<typeof import("../app/components/app-specific/dialogs/ammunition/AmmunitionDetails.vue")['default']>
export const LazyAppSpecificDialogsAmmunitionModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/ammunition/AmmunitionModal.vue")['default']>
export const LazyAppSpecificDialogsAmmunitionTypeModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/ammunition/AmmunitionTypeModal.vue")['default']>
export const LazyAppSpecificDialogsAmmunitionRegisterAmmoType: LazyComponent<typeof import("../app/components/app-specific/dialogs/ammunition/RegisterAmmoType.vue")['default']>
export const LazyAppSpecificDialogsArmsregisterCreateArmoryModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/armsregister/CreateArmoryModal.vue")['default']>
export const LazyAppSpecificDialogsArmsregisterDisposeFireArm: LazyComponent<typeof import("../app/components/app-specific/dialogs/armsregister/DisposeFireArm.vue")['default']>
export const LazyAppSpecificDialogsArmsregisterFireArmsDetails: LazyComponent<typeof import("../app/components/app-specific/dialogs/armsregister/FireArmsDetails.vue")['default']>
export const LazyAppSpecificDialogsArmsregisterRecordFireArm: LazyComponent<typeof import("../app/components/app-specific/dialogs/armsregister/RecordFireArm.vue")['default']>
export const LazyAppSpecificDialogsArmsregisterRegisterFireArm: LazyComponent<typeof import("../app/components/app-specific/dialogs/armsregister/RegisterFireArm.vue")['default']>
export const LazyAppSpecificDialogsArmsregisterReviewFireArm: LazyComponent<typeof import("../app/components/app-specific/dialogs/armsregister/ReviewFireArm.vue")['default']>
export const LazyAppSpecificDialogsBranchModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/branch/BranchModal.vue")['default']>
export const LazyAppSpecificDialogsFirearmIssueFireArm: LazyComponent<typeof import("../app/components/app-specific/dialogs/firearm/IssueFireArm.vue")['default']>
export const LazyAppSpecificDialogsFirearmReturnFireArm: LazyComponent<typeof import("../app/components/app-specific/dialogs/firearm/ReturnFireArm.vue")['default']>
export const LazyAppSpecificDialogsLocationModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/location/LocationModal.vue")['default']>
export const LazyAppSpecificDialogsRolesRoleModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/roles/RoleModal.vue")['default']>
export const LazyAppSpecificDialogsSecuritydevicesDeviceDetails: LazyComponent<typeof import("../app/components/app-specific/dialogs/securitydevices/DeviceDetails.vue")['default']>
export const LazyAppSpecificDialogsSecuritydevicesDeviceInspection: LazyComponent<typeof import("../app/components/app-specific/dialogs/securitydevices/DeviceInspection.vue")['default']>
export const LazyAppSpecificDialogsSecuritydevicesSecurityDeviceModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/securitydevices/SecurityDeviceModal.vue")['default']>
export const LazyAppSpecificDialogsUsersAddEdit: LazyComponent<typeof import("../app/components/app-specific/dialogs/users/AddEdit.vue")['default']>
export const LazyAppSpecificDialogsUsersInfoField: LazyComponent<typeof import("../app/components/app-specific/dialogs/users/InfoField.vue")['default']>
export const LazyAppSpecificDialogsUsersUserDetails: LazyComponent<typeof import("../app/components/app-specific/dialogs/users/UserDetails.vue")['default']>
export const LazyAppSpecificDialogsUsersUserModal: LazyComponent<typeof import("../app/components/app-specific/dialogs/users/UserModal.vue")['default']>
export const LazyAppSpecificFormsAllocationForm: LazyComponent<typeof import("../app/components/app-specific/forms/AllocationForm.vue")['default']>
export const LazyAppSpecificFormsAmmunitionForm: LazyComponent<typeof import("../app/components/app-specific/forms/AmmunitionForm.vue")['default']>
export const LazyAppSpecificFormsCreateIssuanceForm: LazyComponent<typeof import("../app/components/app-specific/forms/CreateIssuanceForm.vue")['default']>
export const LazyAppSpecificFormsFireArmForm: LazyComponent<typeof import("../app/components/app-specific/forms/FireArmForm.vue")['default']>
export const LazyAppSpecificFormsFirearmReturnDialog: LazyComponent<typeof import("../app/components/app-specific/forms/FirearmReturnDialog.vue")['default']>
export const LazyAppSpecificFormsLoginForm: LazyComponent<typeof import("../app/components/app-specific/forms/LoginForm.vue")['default']>
export const LazyAppSpecificFormsRoleForm: LazyComponent<typeof import("../app/components/app-specific/forms/RoleForm.vue")['default']>
export const LazyAppSpecificFormsSetupBranchForm: LazyComponent<typeof import("../app/components/app-specific/forms/SetupBranchForm.vue")['default']>
export const LazyAppSpecificFormsUserForm: LazyComponent<typeof import("../app/components/app-specific/forms/UserForm.vue")['default']>
export const LazyAppSpecificPartialPageAmmunitions: LazyComponent<typeof import("../app/components/app-specific/partial-page/ammunitions.vue")['default']>
export const LazyAppSpecificPartialPageFirearms: LazyComponent<typeof import("../app/components/app-specific/partial-page/firearms.vue")['default']>
export const LazyAppSpecificPartialPageKits: LazyComponent<typeof import("../app/components/app-specific/partial-page/kits.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAccordion: LazyComponent<typeof import("../app/components/ui/accordion/index")['Accordion']>
export const LazyAccordionContent: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionContent']>
export const LazyAccordionItem: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionItem']>
export const LazyAccordionTrigger: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionTrigger']>
export const LazyAlert: LazyComponent<typeof import("../app/components/ui/alert/index")['Alert']>
export const LazyAlertDescription: LazyComponent<typeof import("../app/components/ui/alert/index")['AlertDescription']>
export const LazyAlertTitle: LazyComponent<typeof import("../app/components/ui/alert/index")['AlertTitle']>
export const LazyAlertDialog: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']>
export const LazyAlertDialogAction: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']>
export const LazyAlertDialogCancel: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
export const LazyAlertDialogContent: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']>
export const LazyAlertDialogDescription: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
export const LazyAlertDialogFooter: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
export const LazyAlertDialogHeader: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
export const LazyAlertDialogTitle: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
export const LazyAlertDialogTrigger: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
export const LazyAvatar: LazyComponent<typeof import("../app/components/ui/avatar/index")['Avatar']>
export const LazyAvatarFallback: LazyComponent<typeof import("../app/components/ui/avatar/index")['AvatarFallback']>
export const LazyAvatarImage: LazyComponent<typeof import("../app/components/ui/avatar/index")['AvatarImage']>
export const LazyBadge: LazyComponent<typeof import("../app/components/ui/badge/index")['Badge']>
export const LazyBreadcrumb: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['Breadcrumb']>
export const LazyBreadcrumbEllipsis: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
export const LazyBreadcrumbItem: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbItem']>
export const LazyBreadcrumbLink: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbLink']>
export const LazyBreadcrumbList: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbList']>
export const LazyBreadcrumbPage: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbPage']>
export const LazyBreadcrumbSeparator: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index")['Button']>
export const LazyCalendar: LazyComponent<typeof import("../app/components/ui/calendar/index")['Calendar']>
export const LazyCalendarCell: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarCell']>
export const LazyCalendarCellTrigger: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarCellTrigger']>
export const LazyCalendarGrid: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGrid']>
export const LazyCalendarGridBody: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridBody']>
export const LazyCalendarGridHead: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridHead']>
export const LazyCalendarGridRow: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridRow']>
export const LazyCalendarHeadCell: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeadCell']>
export const LazyCalendarHeader: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeader']>
export const LazyCalendarHeading: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeading']>
export const LazyCalendarNextButton: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarNextButton']>
export const LazyCalendarPrevButton: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarPrevButton']>
export const LazyCard: LazyComponent<typeof import("../app/components/ui/card/index")['Card']>
export const LazyCardAction: LazyComponent<typeof import("../app/components/ui/card/index")['CardAction']>
export const LazyCardContent: LazyComponent<typeof import("../app/components/ui/card/index")['CardContent']>
export const LazyCardDescription: LazyComponent<typeof import("../app/components/ui/card/index")['CardDescription']>
export const LazyCardFooter: LazyComponent<typeof import("../app/components/ui/card/index")['CardFooter']>
export const LazyCardHeader: LazyComponent<typeof import("../app/components/ui/card/index")['CardHeader']>
export const LazyCardTitle: LazyComponent<typeof import("../app/components/ui/card/index")['CardTitle']>
export const LazyCheckbox: LazyComponent<typeof import("../app/components/ui/checkbox/index")['Checkbox']>
export const LazyCollapsible: LazyComponent<typeof import("../app/components/ui/collapsible/index")['Collapsible']>
export const LazyCollapsibleContent: LazyComponent<typeof import("../app/components/ui/collapsible/index")['CollapsibleContent']>
export const LazyCollapsibleTrigger: LazyComponent<typeof import("../app/components/ui/collapsible/index")['CollapsibleTrigger']>
export const LazyDialog: LazyComponent<typeof import("../app/components/ui/dialog/index")['Dialog']>
export const LazyDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogClose']>
export const LazyDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogContent']>
export const LazyDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogDescription']>
export const LazyDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogFooter']>
export const LazyDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogHeader']>
export const LazyDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogOverlay']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogScrollContent']>
export const LazyDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTitle']>
export const LazyDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTrigger']>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyEmpty: LazyComponent<typeof import("../app/components/ui/empty/index")['Empty']>
export const LazyEmptyContent: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyContent']>
export const LazyEmptyDescription: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyDescription']>
export const LazyEmptyHeader: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyHeader']>
export const LazyEmptyMedia: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyMedia']>
export const LazyEmptyTitle: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyTitle']>
export const LazyField: LazyComponent<typeof import("../app/components/ui/field/index")['Field']>
export const LazyFieldContent: LazyComponent<typeof import("../app/components/ui/field/index")['FieldContent']>
export const LazyFieldDescription: LazyComponent<typeof import("../app/components/ui/field/index")['FieldDescription']>
export const LazyFieldError: LazyComponent<typeof import("../app/components/ui/field/index")['FieldError']>
export const LazyFieldGroup: LazyComponent<typeof import("../app/components/ui/field/index")['FieldGroup']>
export const LazyFieldLabel: LazyComponent<typeof import("../app/components/ui/field/index")['FieldLabel']>
export const LazyFieldLegend: LazyComponent<typeof import("../app/components/ui/field/index")['FieldLegend']>
export const LazyFieldSeparator: LazyComponent<typeof import("../app/components/ui/field/index")['FieldSeparator']>
export const LazyFieldSet: LazyComponent<typeof import("../app/components/ui/field/index")['FieldSet']>
export const LazyFieldTitle: LazyComponent<typeof import("../app/components/ui/field/index")['FieldTitle']>
export const LazyInput: LazyComponent<typeof import("../app/components/ui/input/index")['Input']>
export const LazyInputGroup: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroup']>
export const LazyInputGroupAddon: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupAddon']>
export const LazyInputGroupButton: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupButton']>
export const LazyInputGroupInput: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupInput']>
export const LazyInputGroupText: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupText']>
export const LazyInputGroupTextarea: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupTextarea']>
export const LazyInputOTP: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTP']>
export const LazyInputOTPGroup: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTPGroup']>
export const LazyInputOTPSeparator: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTPSeparator']>
export const LazyInputOTPSlot: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTPSlot']>
export const LazyLabel: LazyComponent<typeof import("../app/components/ui/label/index")['Label']>
export const LazyNativeSelect: LazyComponent<typeof import("../app/components/ui/native-select/index")['NativeSelect']>
export const LazyNativeSelectOptGroup: LazyComponent<typeof import("../app/components/ui/native-select/index")['NativeSelectOptGroup']>
export const LazyNativeSelectOption: LazyComponent<typeof import("../app/components/ui/native-select/index")['NativeSelectOption']>
export const LazyPagination: LazyComponent<typeof import("../app/components/ui/pagination/index")['Pagination']>
export const LazyPaginationContent: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationContent']>
export const LazyPaginationEllipsis: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationEllipsis']>
export const LazyPaginationFirst: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationFirst']>
export const LazyPaginationItem: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationItem']>
export const LazyPaginationLast: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationLast']>
export const LazyPaginationNext: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationNext']>
export const LazyPaginationPrev: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationPrev']>
export const LazySelect: LazyComponent<typeof import("../app/components/ui/select/index")['Select']>
export const LazySelectContent: LazyComponent<typeof import("../app/components/ui/select/index")['SelectContent']>
export const LazySelectGroup: LazyComponent<typeof import("../app/components/ui/select/index")['SelectGroup']>
export const LazySelectItem: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItem']>
export const LazySelectItemText: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItemText']>
export const LazySelectLabel: LazyComponent<typeof import("../app/components/ui/select/index")['SelectLabel']>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollDownButton']>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollUpButton']>
export const LazySelectSeparator: LazyComponent<typeof import("../app/components/ui/select/index")['SelectSeparator']>
export const LazySelectTrigger: LazyComponent<typeof import("../app/components/ui/select/index")['SelectTrigger']>
export const LazySelectValue: LazyComponent<typeof import("../app/components/ui/select/index")['SelectValue']>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index")['Separator']>
export const LazySheet: LazyComponent<typeof import("../app/components/ui/sheet/index")['Sheet']>
export const LazySheetClose: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetClose']>
export const LazySheetContent: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetContent']>
export const LazySheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetDescription']>
export const LazySheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetFooter']>
export const LazySheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetHeader']>
export const LazySheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTitle']>
export const LazySheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTrigger']>
export const LazySidebar: LazyComponent<typeof import("../app/components/ui/sidebar/index")['Sidebar']>
export const LazySidebarContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarContent']>
export const LazySidebarFooter: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarFooter']>
export const LazySidebarGroup: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroup']>
export const LazySidebarGroupAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']>
export const LazySidebarGroupContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']>
export const LazySidebarGroupLabel: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']>
export const LazySidebarHeader: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarHeader']>
export const LazySidebarInput: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInput']>
export const LazySidebarInset: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInset']>
export const LazySidebarMenu: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenu']>
export const LazySidebarMenuAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']>
export const LazySidebarMenuBadge: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']>
export const LazySidebarMenuButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']>
export const LazySidebarMenuItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']>
export const LazySidebarMenuSkeleton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
export const LazySidebarMenuSub: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']>
export const LazySidebarMenuSubButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
export const LazySidebarMenuSubItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
export const LazySidebarProvider: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarProvider']>
export const LazySidebarRail: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarRail']>
export const LazySidebarSeparator: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']>
export const LazySidebarTrigger: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']>
export const LazySkeleton: LazyComponent<typeof import("../app/components/ui/skeleton/index")['Skeleton']>
export const LazyToaster: LazyComponent<typeof import("../app/components/ui/sonner/index")['Toaster']>
export const LazySpinner: LazyComponent<typeof import("../app/components/ui/spinner/index")['Spinner']>
export const LazyStepper: LazyComponent<typeof import("../app/components/ui/stepper/index")['Stepper']>
export const LazyStepperDescription: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperDescription']>
export const LazyStepperIndicator: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperIndicator']>
export const LazyStepperItem: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperItem']>
export const LazyStepperSeparator: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperSeparator']>
export const LazyStepperTitle: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperTitle']>
export const LazyStepperTrigger: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperTrigger']>
export const LazySwitch: LazyComponent<typeof import("../app/components/ui/switch/index")['Switch']>
export const LazyTable: LazyComponent<typeof import("../app/components/ui/table/index")['Table']>
export const LazyTableBody: LazyComponent<typeof import("../app/components/ui/table/index")['TableBody']>
export const LazyTableCaption: LazyComponent<typeof import("../app/components/ui/table/index")['TableCaption']>
export const LazyTableCell: LazyComponent<typeof import("../app/components/ui/table/index")['TableCell']>
export const LazyTableEmpty: LazyComponent<typeof import("../app/components/ui/table/index")['TableEmpty']>
export const LazyTableFooter: LazyComponent<typeof import("../app/components/ui/table/index")['TableFooter']>
export const LazyTableHead: LazyComponent<typeof import("../app/components/ui/table/index")['TableHead']>
export const LazyTableHeader: LazyComponent<typeof import("../app/components/ui/table/index")['TableHeader']>
export const LazyTableRow: LazyComponent<typeof import("../app/components/ui/table/index")['TableRow']>
export const LazyTabs: LazyComponent<typeof import("../app/components/ui/tabs/index")['Tabs']>
export const LazyTabsContent: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsContent']>
export const LazyTabsList: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsList']>
export const LazyTabsTrigger: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsTrigger']>
export const LazyTextarea: LazyComponent<typeof import("../app/components/ui/textarea/index")['Textarea']>
export const LazyTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index")['Tooltip']>
export const LazyTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipContent']>
export const LazyTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipProvider']>
export const LazyTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_926721a1675078e34d54c6faaaeb929a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_5a195fceced10ac9fea902dd8b70b305/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
